# Generated by Django 3.0.4 on 2020-03-17 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, null=True)),
                ('dest', models.CharField(blank=True, max_length=100)),
                ('imageFile', models.ImageField(blank=True, null=True, upload_to='places/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=1000, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('imageFile', models.ImageField(blank=True, null=True, upload_to='hotels_and_resto/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=1000, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Resto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('imageFile', models.ImageField(blank=True, null=True, upload_to='hotels_and_resto/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=1000, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_planned', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('booker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.Booker')),
                ('flights', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.Flights')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedFlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('planned', models.BooleanField(default=False, verbose_name='Planned')),
                ('items', models.ManyToManyField(null=True, to='plan.Flights')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
